apiVersion: v1
kind: ConfigMap
metadata:
  name: tornjak-agent
  namespace: spire
data:
  server.conf: |
    server {
      spire_socket_path = "unix:///tmp/spire-server/private/api.sock"

      http {
        enabled = true
        listen_port = ":10000"
      }

    }

    plugins {
      DataStore "sql" {
        plugin_data {
          drivername = "sqlite3"
          filename = "/run/spire/data/tornjak.sqlite3"
        }
      }
    }
